name: Deploy - SelfService - Backend

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  PRERELEASE_BRANCHES: "" # Comma separated list of prerelease branch names. 'alpha,rc, ...'
  SOURCE_PATH: "Source/SelfService/Backend"
  DOCKER_FILE: "Source/SelfService/Backend/Dockerfile"

jobs:
  changes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.filter.outputs.src }}
      should-publish: ${{ steps.context.outputs.should-publish }}
      release-type: ${{ steps.context.outputs.release-type }}
      current-version: ${{ steps.context.outputs.current-version }}
      pr-body: ${{ steps.context.outputs.pr-body }}
      pr-url: ${{ steps.context.outputs.pr-url }}
      next-version: ${{ steps.increment-version.outputs.next-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - '${{ env.SOURCE_PATH }}/**'

      - name: Establish context
        id: context
        uses: dolittle/establish-context-action@v2
        with:
          prerelease-branches: ${{ env.PRERELEASE_BRANCHES }}
          version-file: ${{ env.SOURCE_PATH }}/version.json

      - name: Increment version
        id: increment-version
        if: ${{ steps.context.outputs.should-publish == 'true' }}
        uses: dolittle/increment-version-action@v2
        with:
          version: ${{ steps.context.outputs.current-version }}
          release-type: ${{ steps.context.outputs.release-type }}

  release:
    needs: changes
    if: needs.changes.outputs.has-changes == 'true' && needs.changes.outputs.should-publish == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Establish context
        id: context
        uses: dolittle/establish-context-action@v2
        with:
          prerelease-branches: ${{ env.PRERELEASE_BRANCHES }}
          version-file: ${{ env.SOURCE_PATH }}/version.json

      - name: Write version info
        uses: dolittle/write-version-to-file-action@v2
        with:
          path: ${{ env.SOURCE_PATH }}/version.json
          version: ${{ needs.changes.outputs.next-version }}
          merge-strategy: rebase

      - name: Prepend to Changelog
        if: needs.changes.outputs.release-type != 'prerelease'
        uses: dolittle/add-to-changelog-action@v2
        with:
          version: ${{ needs.changes.outputs.next-version }}
          body: ${{ needs.changes.outputs.pr-body }}
          pr-url: ${{ needs.changes.outputs.pr-url }}
          changelog-path: ${{ env.SOURCE_PATH }}/CHANGELOG.md
          user-email: build@dolittle.com
          user-name: dolittle-build

      - name: Create GitHub Release
        uses: dolittle/github-release-action@v2
        with:
          token: ${{  secrets.BUILD_PAT  }}
          version: ${{ needs.changes.outputs.next-version }}
          body: ${{ needs.changes.outputs.pr-body }}
          microservice: SelfService-Backend

      - name: Push semantic tag to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ env.SOURCE_PATH }}
          file: ./${{ env.DOCKER_FILE }}
          tags: dolittle/self-service-backend:${{ needs.changes.outputs.next-version }}

      - name: Push latest tag to Docker Hub
        uses: docker/build-push-action@v2
        if: steps.context.outputs.release-type != 'prerelease'
        with:
          push: true
          context: ${{ env.SOURCE_PATH }}
          file: ./${{ env.DOCKER_FILE }}
          tags: dolittle/self-service-backend:latest

  deploy-dev:
    needs:
      - changes
      - release
    name: Deploy SelfService Backend to development
    uses: ./.github/workflows/update-container-image.yml
    secrets: inherit
    with:
      namespace: application-fe7736bb-57fc-4166-bb91-6954f4dd4eb7
      deployment: dev-selfservicebackend
      image: dolittle/self-service-backend:${{ needs.changes.outputs.next-version }}
      environment: dev
      environment-url: https://dev.dolittle.studio/

  deploy-prod:
    needs:
      - changes
      - release
    name: Deploy SelfService Backend to production
    uses: ./.github/workflows/update-container-image.yml
    secrets: inherit
    with:
      namespace: application-fe7736bb-57fc-4166-bb91-6954f4dd4eb7
      deployment: prod-selfservicebackend
      image: dolittle/self-service-backend:${{ needs.changes.outputs.next-version }}
      environment: prod
      environment-url: https://dolittle.studio/
